team8-c-sharp-week9-pair-exercises/13-Capstone/Capstone.Web/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Capstone.Web.DAL;
using Capstone.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Capstone.Web.Controllers
{
    public class SurveyController : Controller
    {
        ISurveyDao surveyDao;
        IParkDao parkDao;

        public SurveyController(ISurveyDao surveyDao, IParkDao parkDao) //we initialize our park and survey
        {
            this.surveyDao = surveyDao;
            this.parkDao = parkDao;
        }

        public IActionResult Index() //we create a new survey and get a list of parks
        {
            Survey survey = new Survey();
            survey.ParkList = parkDao.GetAllParks();

            return View(survey); //create new view bound to our survey
        }

        [HttpPost]
        [ValidateAntiForgeryToken] 
        public IActionResult Index(Survey survey)
        {
            if(!ModelState.IsValid) //if it is not valid ..we don't submit our survey and go back to index
            {
                survey.ParkList = parkDao.GetAllParks();
                return View(survey);
            }

            surveyDao.SaveSurvey(survey);//submit our survey

            return RedirectToAction("FavoritePark"); //otherwise we redirect to favorite park
        }
        public IActionResult FavoritePark()
        {
            List<Survey> surveys = surveyDao.FavoritePark();
            return View(surveys); // binds of list of surveys to fav park
        }
    }
}

team8-c-sharp-week9-pair-exercises/13-Capstone/Capstone.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - National Parks Geek.Web</title>


    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                <img src="~/img/logo.png" alt="National Parks Geek logo" />
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li id="home"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li id="survey"><a asp-area="" asp-controller="Survey" asp-action="Index">Survey</a></li>
                    </ul>
                </div>
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Capstone.Web</a>*@
            </div>

        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Team8 Productions</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>