team6-c-sharp-week8-pair-exercises/06-Forms-and-Controllers-HTTP-GET/student-pair/SSGeek.Web/Controllers/CalculatorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SSGeek.Web.Models;

namespace SSGeek.Web.Controllers
{
    public class CalculatorsController : Controller
    {
        // INSTRUCTIONS
        // As a part of each exercise you will need to 
        // - develop a view for AlienAge, AlienWeight, and AlienTravel that displays a form to submit data
        // - create a new action to process the form submission (e.g. AlienAgeResult, AlienWeightResult, etc.)
        // - create a view that displays the submitted form result

        
        // GET: Calculators/AlienWeight
        public ActionResult AlienWeight()
        {
            AlienWeightModel alienWeight = new AlienWeightModel();
            return View(alienWeight);
        }

        // GET: calcualtors/alienweightresult?planet=xyz&weight=123
        public ActionResult AlienWeightResult(AlienWeightModel model)
        {
            return View(model);
        }

        public ActionResult AlienAge()
        {
            AlienAgeModel alienAge = new AlienAgeModel();
            return View(alienAge);
        }

        public ActionResult AlienAgeResult(AlienAgeModel model)
        {
            return View(model);
        }

        private List<SelectListItem> planets = new List<SelectListItem>()
        {
            new SelectListItem() { Text = "Mercury" },
            new SelectListItem() { Text = "Venus" },
            new SelectListItem() { Text = "Mars" },
            new SelectListItem() { Text = "Jupiter" },
            new SelectListItem() { Text = "Saturn" },
            new SelectListItem() { Text = "Neptune" },
            new SelectListItem() { Text = "Uranus" }
        };

        private List<SelectListItem> transportationModes = new List<SelectListItem>()
        {
            new SelectListItem() { Text = "Walking", Value="walking" },
            new SelectListItem() { Text = "Car", Value = "car" },
            new SelectListItem() { Text = "Bullet Train", Value = "bullet train" },
            new SelectListItem() { Text = "Boeing 747", Value = "boeing 747" },
            new SelectListItem() { Text = "Concorde", Value = "concorde" }
        };

        public ActionResult AlienTravel(List<SelectListItem> planets, List<SelectListItem> transportationModes)
        {
            AlienTravelModel alienTravel = new AlienTravelModel();
            return View(alienTravel);
        }

        public ActionResult AlienTravelResult(AlienTravelModel model)
        {          
            return View(model);
        }

    }

}

team6-c-sharp-week8-pair-exercises/06-Forms-and-Controllers-HTTP-GET/student-pair/SSGeek.Web/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SSGeek.Web.DAL;
using SSGeek.Web.Extensions;
using SSGeek.Web.Models;

namespace SSGeek.Web.Controllers
{
    public class StoreController : Controller
    {
        private IProductDAO productDAO;
        public StoreController(IProductDAO productDAO)
        {
            this.productDAO = productDAO;
        }

        public ActionResult Index()
        {
            IList<Product> products = productDAO.GetProducts();
            return View(products);
        }

        public ActionResult Detail(int id)
        {
            Product product = new Product();
            product = productDAO.GetProduct(id);
            return View(product);
        }

        public ActionResult ViewCart()
        {
            ShoppingCart cart = GetActiveShoppingCart();
            return View(cart);
        }

        [HttpPost]
        public ActionResult AddToCart(Product product, int quantity)
        {
            product = productDAO.GetProduct(product.Id);
            ShoppingCart cart = GetActiveShoppingCart();
            cart.AddToCart(product, quantity);
            SaveActiveShoppingCart(cart);

            return RedirectToAction("ViewCart");
        }

        private ShoppingCart GetActiveShoppingCart()
        {
            ShoppingCart cart = null;
           
            if (HttpContext.Session.Get<ShoppingCart>("Shopping_Cart") == null)
            {
                cart = new ShoppingCart();
                SaveActiveShoppingCart(cart);
            }
            else
            {
                cart = HttpContext.Session.Get<ShoppingCart>("Shopping_Cart");
            }

            return cart;
        }

        private void SaveActiveShoppingCart(ShoppingCart cart)
        {
            HttpContext.Session.Set("Shopping_Cart", cart);
        }

    }
}

team6-c-sharp-week8-pair-exercises/06-Forms-and-Controllers-HTTP-GET/student-pair/SSGeek.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SSGeek.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <header>
        <img src="~/images/ssg_logo.png" alt="Solar System Geek logo" />
        <h1>The Solar System</h1>
        <p>The Solar System formed 4.6 billion years ago from the gravitational collapse of a giant interstellar molecular cloud. The vast majority of the system's mass is in the Sun, with most of the remaining mass contained in Jupiter. The four smaller inner planets, Mercury, Venus, Earth and Mars, are terrestrial planets, being primarily composed of rock and metal. The four outer planets are giant planets, being substantially more massive than the terrestrials. The two largest, Jupiter and Saturn, are gas giants, being composed mainly of hydrogen and helium; the two outermost planets, Uranus and Neptune, are ice giants, being composed largely of substances with relatively high melting points compared with hydrogen and helium, called ices, such as water, ammonia and methane. All planets have almost circular orbits that lie within a nearly flat disc called the ecliptic. </p>
    </header>
    <nav>
        <h2>Explore The Solar System</h2>
        <p> Use these state of the art web applications to learn more about the solar system! </p>
        <ul>
            <li><a asp-action="AlienAge" asp-controller="Calculators">Alien Age</a></li>
            <li><a asp-action="AlienWeight" asp-controller="Calculators">Alien Weight</a></li>
            <li><a asp-action="AlienTravel" asp-controller="Calculators">Alien Travel Time</a></li>
            <li><a asp-action="Index" asp-controller="Forum">Space Forum</a></li>
            <li><a asp-action="Index" asp-controller="Store">Space Store</a></li>
        </ul>
    </nav>

    @RenderBody()
    
    <footer>
        <p>&copy; 2018 - SSGeek.Web</p>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>